import type { Product } from './types'

export const products: Product[] = [
  {
    id: 'baron',
    slug: 'baron',
    name: 'Baron',
    description: 'Начальный донат-ранг. Идеально для тех, кто хочет поддержать сервер.',
    color: '#9B8B6E',
    order: 1,
    active: true,
    perks: [
      'Префикс [Baron] в чате',
      'Цветной ник',
      'Приват 1 чанк',
      'Доступ к /kit baron',
      'Команда /hat',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 99, commands: ['lp user {username} parent addtemp baron 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 249, commands: ['lp user {username} parent addtemp baron 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 499, commands: ['lp user {username} parent add baron'] },
    ],
  },
  {
    id: 'guard',
    slug: 'guard',
    name: 'Guard',
    description: 'Базовая привилегия. Больше команд и возможностей для игры.',
    color: '#5B8EAD',
    order: 2,
    active: true,
    perks: [
      'Всё из Baron',
      'Префикс [Guard] в чате',
      'Приват 3 чанка',
      'Доступ к /kit guard',
      'Команда /nick',
      'Команда /fly в лобби',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 149, commands: ['lp user {username} parent addtemp guard 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 399, commands: ['lp user {username} parent addtemp guard 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 799, commands: ['lp user {username} parent add guard'] },
    ],
  },
  {
    id: 'hero',
    slug: 'hero',
    name: 'Hero',
    description: 'Средний популярный ранг. Идеальный баланс цены и привилегий.',
    color: '#4CAF50',
    order: 3,
    active: true,
    perks: [
      'Всё из Guard',
      'Префикс [Hero] в чате',
      'Приват 5 чанков',
      'Доступ к /kit hero',
      'Команда /workbench',
      'Команда /enderchest',
      'Цветной чат',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 249, commands: ['lp user {username} parent addtemp hero 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 649, commands: ['lp user {username} parent addtemp hero 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1299, commands: ['lp user {username} parent add hero'] },
    ],
  },
  {
    id: 'aspid',
    slug: 'aspid',
    name: 'Aspid',
    description: 'Продвинутый ранг для серьёзных игроков сервера.',
    color: '#9C27B0',
    order: 4,
    active: true,
    perks: [
      'Всё из Hero',
      'Префикс [Aspid] в чате',
      'Приват 10 чанков',
      'Доступ к /kit aspid',
      'Команда /feed',
      'Команда /heal',
      'Приоритет в очереди',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 349, commands: ['lp user {username} parent addtemp aspid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 899, commands: ['lp user {username} parent addtemp aspid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1799, commands: ['lp user {username} parent add aspid'] },
    ],
  },
  {
    id: 'squid',
    slug: 'squid',
    name: 'Squid',
    description: 'Высокий ранг с расширенными возможностями и привилегиями.',
    color: '#FF9800',
    order: 5,
    active: true,
    perks: [
      'Всё из Aspid',
      'Префикс [Squid] в чате',
      'Приват 20 чанков',
      'Доступ к /kit squid',
      'Команда /fly на выживании',
      'Команда /tp к игрокам',
      'Значок в TAB списке',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 499, commands: ['lp user {username} parent addtemp squid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1299, commands: ['lp user {username} parent addtemp squid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 2599, commands: ['lp user {username} parent add squid'] },
    ],
  },
  {
    id: 'head',
    slug: 'head',
    name: 'Head',
    description: 'Почти максимальный ранг. Доступ к эксклюзивным функциям сервера.',
    color: '#F44336',
    order: 6,
    active: true,
    perks: [
      'Всё из Squid',
      'Префикс [Head] в чате',
      'Приват 50 чанков',
      'Доступ к /kit head',
      'Команда /god',
      'VIP-чат',
      'Эксклюзивный cosmetic',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 699, commands: ['lp user {username} parent addtemp head 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1799, commands: ['lp user {username} parent addtemp head 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 3599, commands: ['lp user {username} parent add head'] },
    ],
  },
  {
    id: 'elite',
    slug: 'elite',
    name: 'Elite',
    description: 'Максимальный ранг NATUX WORLD. Полный доступ ко всем привилегиям.',
    color: '#FF2B4F',
    order: 7,
    active: true,
    perks: [
      'Всё из Head',
      'Префикс [ELITE] в чате',
      'Безлимитный приват',
      'Доступ к /kit elite',
      'Все команды сервера',
      'Личный Discord-канал',
      'Значок на сайте',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 999, commands: ['lp user {username} parent addtemp elite 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 2499, commands: ['lp user {username} parent addtemp elite 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 4999, commands: ['lp user {username} parent add elite'] },
    ],
  },
]
