import type { Product } from './types'

export const products: Product[] = [
  // ─── 1. BARON ────────────────────────────────────────────────────────────
  {
    id: 'baron',
    slug: 'baron',
    name: 'Baron',
    description: 'Начальный ранг для тех, кто хочет поддержать сервер и получить базовые удобства.',
    color: '#9B8B6E',
    order: 1,
    active: true,
    perks: [
      'Префикс §6[Baron]§r в чате',
      'Цветной ник (золотой)',
      'Приват до 3 чанков',
      'Кит /kit baron раз в 3 дня',
      'Команда /hat — надеть блок как шлем',
      'Команда /back — вернуться на точку смерти',
      'Команда /me — эмоции в чате',
      'Вход через VIP-слот (+1 к лимиту)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 99, commands: ['lp user {username} parent addtemp baron 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 249, commands: ['lp user {username} parent addtemp baron 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 499, commands: ['lp user {username} parent add baron'] },
    ],
  },

  // ─── 2. KNIGHT ───────────────────────────────────────────────────────────
  {
    id: 'knight',
    slug: 'knight',
    name: 'Knight',
    description: 'Рыцарь сервера. Улучшенная защита, боевые привилегии и доступ к закрытым зонам.',
    color: '#A8A8A8',
    order: 2,
    active: true,
    badge: 'НОВИНКА',
    perks: [
      'Всё из Baron',
      'Префикс §7[Knight]§r в чате',
      'Цветной ник (серебряный)',
      'Приват до 5 чанков',
      'Кит /kit knight раз в 3 дня (улучшенная броня)',
      'Команда /tpa — запросить телепорт к игроку',
      'Команда /sit — сесть в любом месте',
      'Команда /jump — прыгнуть вперёд на 5 блоков',
      'Сохранение инвентаря при смерти (1 раз в 14 дней)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 120, commands: ['lp user {username} parent addtemp knight 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 299, commands: ['lp user {username} parent addtemp knight 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 599, commands: ['lp user {username} parent add knight'] },
    ],
  },

  // ─── 3. GUARD ────────────────────────────────────────────────────────────
  {
    id: 'guard',
    slug: 'guard',
    name: 'Guard',
    description: 'Страж сервера. Расширенный набор команд, кастомизация и доступ к /fly в лобби.',
    color: '#5B8EAD',
    order: 3,
    active: true,
    perks: [
      'Всё из Knight',
      'Префикс §b[Guard]§r в чате',
      'Цветной ник (голубой)',
      'Приват до 7 чанков',
      'Кит /kit guard раз в 2 дня',
      'Команда /nick — псевдоним в чате',
      'Команда /fly в лобби и на спавне',
      'Команда /seen — когда игрок был онлайн',
      'Кастомный тег в Discord-сервере',
      'Вход через VIP-слот (+2 к лимиту)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 149, commands: ['lp user {username} parent addtemp guard 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 399, commands: ['lp user {username} parent addtemp guard 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 799, commands: ['lp user {username} parent add guard'] },
    ],
  },

  // ─── 4. RANGER ───────────────────────────────────────────────────────────
  {
    id: 'ranger',
    slug: 'ranger',
    name: 'Ranger',
    description: 'Охотник и следопыт. Скорость, охота и расширенная навигация по миру.',
    color: '#2E7D32',
    order: 4,
    active: true,
    perks: [
      'Всё из Guard',
      'Префикс §2[Ranger]§r в чате',
      'Цветной ник (тёмно-зелёный)',
      'Приват до 10 чанков',
      'Кит /kit ranger раз в 2 дня (луки, стрелы)',
      'Команда /near — список игроков в радиусе',
      'Команда /speed — изменить скорость ходьбы',
      'Команда /compass — направление в чате',
      'Команда /biome — узнать биом под ногами',
      'Команда /depth — узнать глубину нахождения',
      'Доп. слоты в аукционе (+3)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 199, commands: ['lp user {username} parent addtemp ranger 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 499, commands: ['lp user {username} parent addtemp ranger 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 999, commands: ['lp user {username} parent add ranger'] },
    ],
  },

  // ─── 5. HERO ─────────────────────────────────────────────────────────────
  {
    id: 'hero',
    slug: 'hero',
    name: 'Hero',
    description: 'Самый популярный ранг. Оптимальный баланс цены, привилегий и удобства игры.',
    color: '#4CAF50',
    order: 5,
    active: true,
    badge: 'ТОП ПРОДАЖ',
    popular: true,
    perks: [
      'Всё из Ranger',
      'Префикс §a[Hero]§r в чате',
      'Цветной ник (зелёный)',
      'Приват до 15 чанков',
      'Кит /kit hero раз в 1 день',
      'Команда /workbench — верстак в кармане',
      'Команда /enderchest — эндер-сундук в кармане',
      'Команда /anvil — наковальня в кармане',
      'Цветные сообщения в чате',
      'Сохранение инвентаря (1 раз в 7 дней)',
      'Приоритет входа (+3 к лимиту)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 249, commands: ['lp user {username} parent addtemp hero 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 649, commands: ['lp user {username} parent addtemp hero 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1299, commands: ['lp user {username} parent add hero'] },
    ],
  },

  // ─── 6. SHADOW ───────────────────────────────────────────────────────────
  {
    id: 'shadow',
    slug: 'shadow',
    name: 'Shadow',
    description: 'Мастер теней. Невидимость, скрытность и способности, которых нет у других.',
    color: '#7C3AED',
    order: 6,
    active: true,
    badge: 'НОВИНКА',
    perks: [
      'Всё из Hero',
      'Префикс §5[Shadow]§r в чате',
      'Цветной ник (фиолетовый)',
      'Приват до 20 чанков',
      'Кит /kit shadow раз в 1 день (зачарованная броня)',
      'Команда /vanish — временная невидимость (30 сек, раз в час)',
      'Команда /pweather — личная погода',
      'Команда /ptime — личное время суток',
      'Скрытие из списка /list (по желанию)',
      'Эффект ночного видения в темноте',
      'Сохранение инвентаря (3 раза в неделю)',
      'Доп. слоты в аукционе (+5)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 299, commands: ['lp user {username} parent addtemp shadow 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 799, commands: ['lp user {username} parent addtemp shadow 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1599, commands: ['lp user {username} parent add shadow'] },
    ],
  },

  // ─── 7. ASPID ────────────────────────────────────────────────────────────
  {
    id: 'aspid',
    slug: 'aspid',
    name: 'Aspid',
    description: 'Продвинутый ранг для серьёзных игроков. Выживай дольше, добывай эффективнее.',
    color: '#9C27B0',
    order: 7,
    active: true,
    perks: [
      'Всё из Shadow',
      'Префикс §d[Aspid]§r в чате',
      'Цветной ник (пурпурный)',
      'Приват до 25 чанков',
      'Кит /kit aspid раз в 12 часов',
      'Команда /feed — насытиться (раз в 5 мин)',
      'Команда /heal — восстановить здоровье (раз в 10 мин)',
      'Команда /trash — встроенная корзина',
      'Команда /condense — сжать предметы в блоки',
      'Приоритет входа (+4 к лимиту)',
      'x1.5 опыт с мобов',
      'Сохранение инвентаря (без ограничений)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 349, commands: ['lp user {username} parent addtemp aspid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 899, commands: ['lp user {username} parent addtemp aspid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1799, commands: ['lp user {username} parent add aspid'] },
    ],
  },

  // ─── 8. WARLORD ──────────────────────────────────────────────────────────
  {
    id: 'warlord',
    slug: 'warlord',
    name: 'Warlord',
    description: 'Военачальник. Командуй полем боя — полёт, сила и боевые привилегии на максимуме.',
    color: '#D97706',
    order: 8,
    active: true,
    badge: 'В ТРЕНДЕ',
    perks: [
      'Всё из Aspid',
      'Префикс §6[Warlord]§r в чате',
      'Цветной ник (янтарный)',
      'Приват до 35 чанков',
      'Кит /kit warlord раз в 8 часов',
      'Команда /fly на выживании (вне PvP-зоны)',
      'Команда /tp — телепорт к игрокам',
      'Команда /tphere — вызвать игрока к себе',
      'Команда /invsee — просмотр инвентаря',
      'Эффект силы I постоянно активен',
      'x2 опыт с мобов',
      'Выделение в TAB-листе игроков',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 429, commands: ['lp user {username} parent addtemp warlord 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1099, commands: ['lp user {username} parent addtemp warlord 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 2199, commands: ['lp user {username} parent add warlord'] },
    ],
  },

  // ─── 9. SQUID ────────────────────────────────────────────────────────────
  {
    id: 'squid',
    slug: 'squid',
    name: 'Squid',
    description: 'Высокий ранг с полётом, расширенной телепортацией и дополнительными удобствами.',
    color: '#FF9800',
    order: 9,
    active: true,
    badge: 'ВЫГОДНО',
    perks: [
      'Всё из Warlord',
      'Префикс §6[Squid]§r в чате',
      'Цветной ник (оранжевый)',
      'Приват до 40 чанков',
      'Кит /kit squid раз в 6 часов',
      'Команда /speed — изменить скорость полёта',
      'Команда /back при любом телепорте',
      'Команда /tptoggle — управление TP-запросами',
      'Доступ к /kit seasonal — сезонные киты',
      'x2.5 опыт с мобов',
      'Позиция в верхней части TAB-листа',
      'Приоритет входа (+5 к лимиту)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 499, commands: ['lp user {username} parent addtemp squid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1299, commands: ['lp user {username} parent addtemp squid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 2599, commands: ['lp user {username} parent add squid'] },
    ],
  },

  // ─── 10. PHANTOM ─────────────────────────────────────────────────────────
  {
    id: 'phantom',
    slug: 'phantom',
    name: 'Phantom',
    description: 'Призрак поля боя. Уникальные эффекты, контроль пространства и эксклюзивный cosmetic.',
    color: '#00BCD4',
    order: 10,
    active: true,
    badge: 'НОВИНКА',
    perks: [
      'Всё из Squid',
      'Префикс §3[Phantom]§r в чате',
      'Цветной ник (бирюзовый)',
      'Приват до 50 чанков',
      'Кит /kit phantom раз в 4 часа',
      'Команда /echest — открыть эндер-сундук из любой точки',
      'Команда /disposal — быстрое уничтожение мусора',
      'Эффект ночного видения всегда активен',
      'Particle-эффект вокруг персонажа (призрачные частицы)',
      'Команда /skull — получить голову убитого моба',
      'x3 опыт с мобов',
      'Скрытие из /near и /list (по желанию)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 599, commands: ['lp user {username} parent addtemp phantom 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1549, commands: ['lp user {username} parent addtemp phantom 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 3099, commands: ['lp user {username} parent add phantom'] },
    ],
  },

  // ─── 11. HEAD ────────────────────────────────────────────────────────────
  {
    id: 'head',
    slug: 'head',
    name: 'Head',
    description: 'Почти максимальный ранг. Эксклюзивные функции, личный Discord и максимальный комфорт.',
    color: '#F44336',
    order: 11,
    active: true,
    perks: [
      'Всё из Phantom',
      'Префикс §c[Head]§r в чате',
      'Цветной ник (красный)',
      'Приват до 75 чанков',
      'Кит /kit head раз в 3 часа',
      'Команда /god — режим бога (1 раз в сутки, 30 мин)',
      'Команда /repair — починить предмет в руке (раз в день)',
      'Команда /craft — открыть верстак без блока',
      'Отдельный VIP-чат только для привилегий',
      'Личный текстовый канал в Discord',
      'x3 опыт с убийства мобов',
      'Топ-приоритет подключения к серверу',
      'Дроп редкого лута +25%',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 699, commands: ['lp user {username} parent addtemp head 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1799, commands: ['lp user {username} parent addtemp head 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 3599, commands: ['lp user {username} parent add head'] },
    ],
  },

  // ─── 12. DEMON ───────────────────────────────────────────────────────────
  {
    id: 'demon',
    slug: 'demon',
    name: 'Demon',
    description: 'Тёмная сила сервера. Демонические привилегии, массивные бонусы и страх у противников.',
    color: '#C62828',
    order: 12,
    active: true,
    badge: 'ЛЕГЕНДА',
    perks: [
      'Всё из Head',
      'Префикс §4[Demon]§r в чате (анимированный огонь)',
      'Цветной ник (тёмно-красный)',
      'Приват до 100 чанков',
      'Кит /kit demon раз в 2 часа',
      'Команда /god без ограничений по времени',
      'Команда /repair — чинить любой предмет (без ограничений)',
      'Команда /hat — любой блок или голова игрока',
      'Постоянный эффект силы II',
      'Постоянный эффект скорости II',
      'Огненная частица-аура вокруг персонажа',
      'x4 опыт с мобов',
      'Дроп редкого лута +50%',
      'Личный голосовой канал в Discord',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 849, commands: ['lp user {username} parent addtemp demon 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 2199, commands: ['lp user {username} parent addtemp demon 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 4399, commands: ['lp user {username} parent add demon'] },
    ],
  },

  // ─── 13. ELITE ───────────────────────────────────────────────────────────
  {
    id: 'elite',
    slug: 'elite',
    name: 'Elite',
    description: 'Элита сервера. Все привилегии, все команды, статус легенды NATUX WORLD.',
    color: '#FF2B4F',
    order: 13,
    active: true,
    perks: [
      'Всё из Demon',
      'Префикс §4[ELITE]§r в чате',
      'Безлимитный приват',
      'Кит /kit elite раз в 1 час',
      'Команда /broadcast — объявление на весь сервер (раз в день)',
      'Команда /nick с полным RGB-форматированием',
      'Команда /god постоянно активна',
      'x5 опыт с мобов',
      'Дроп редкого лута +75%',
      'Значок ELITE на сайте',
      'Позиция в самом верху TAB-листа',
      'Эксклюзивный cosmetic-набор',
      'Ранний доступ к обновлениям сервера',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 999, commands: ['lp user {username} parent addtemp elite 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 2499, commands: ['lp user {username} parent addtemp elite 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 4999, commands: ['lp user {username} parent add elite'] },
    ],
  },

  // ─── 14. KING ────────────────────────────────────────────────────────────
  {
    id: 'king',
    slug: 'king',
    name: 'King',
    description: 'Король NATUX WORLD. Абсолютная власть, уникальный статус и привилегии высшего уровня.',
    color: '#FFD700',
    order: 14,
    active: true,
    badge: 'КОРОЛЕВСКИЙ',
    perks: [
      'Всё из Elite',
      'Префикс §e[KING]§r в чате (золотая корона)',
      'RGB-анимированный ник',
      'Безлимитный приват с возможностью рейда',
      'Кит /kit king раз в 30 минут',
      'Команда /broadcast без ограничений',
      'Команда /smite — ударить молнией (в лобби)',
      'Команда /firework — запустить фейерверк',
      'Специальный звуковой эффект при входе на сервер',
      'Золотая королевская аура частиц',
      'x6 опыт с мобов',
      'Дроп редкого лута +100%',
      'Отдельная роль King в Discord',
      'Участие в закрытых King-ивентах',
      'Влияние на голосования об обновлениях',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 1299, commands: ['lp user {username} parent addtemp king 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 3299, commands: ['lp user {username} parent addtemp king 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 6599, commands: ['lp user {username} parent add king'] },
    ],
  },

  // ─── 15. GOD ─────────────────────────────────────────────────────────────
  {
    id: 'god',
    slug: 'god',
    name: 'God',
    description: 'Абсолютный максимум. Единственный в своём роде статус — быть богом NATUX WORLD.',
    color: '#F9FAFB',
    order: 15,
    active: true,
    badge: 'АБСОЛЮТ',
    perks: [
      'Всё из King',
      'Префикс §f✦[GOD]✦§r — уникальный анимированный',
      'Эксклюзивный белый светящийся ник',
      'Безлимитный приват абсолютно везде',
      'Кит /kit god раз в 15 минут (лучшее снаряжение)',
      'Полный доступ ко всем командам сервера',
      'Неуязвимость к урону от среды (лава, падение, огонь)',
      'Команда /god — неуязвимость в бою без ограничений',
      'Команда /fly везде без ограничений',
      'Ослепительная белая аура частиц',
      'Звук грома при входе на сервер',
      'x10 опыт с мобов',
      'Дроп редкого лута +150%',
      'Прямая связь с администрацией',
      'Участие в разработке механик сервера',
      'Вечное упоминание в зале славы на сайте',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 1799, commands: ['lp user {username} parent addtemp god 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 4499, commands: ['lp user {username} parent addtemp god 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 8999, commands: ['lp user {username} parent add god'] },
    ],
  },
]
