import type { Product } from './types'

export const products: Product[] = [
  {
    id: 'baron',
    slug: 'baron',
    name: 'Baron',
    description: 'Начальный донат-ранг. Идеально для тех, кто хочет поддержать сервер и получить базовые удобства.',
    color: '#9B8B6E',
    order: 1,
    active: true,
    perks: [
      'Префикс §6[Baron]§r в чате',
      'Цветной ник (золотой)',
      'Приват до 3 чанков',
      'Кит /kit baron раз в 3 дня',
      'Команда /hat — надеть блок как шлем',
      'Команда /back — вернуться на точку смерти',
      'Команда /me — эмоции в чате',
      'Вход через VIP-слот (+1 к лимиту)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 99, commands: ['lp user {username} parent addtemp baron 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 249, commands: ['lp user {username} parent addtemp baron 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 499, commands: ['lp user {username} parent add baron'] },
    ],
  },
  {
    id: 'guard',
    slug: 'guard',
    name: 'Guard',
    description: 'Базовая привилегия стража. Больше команд, расширенный приват и доступ к кастомизации.',
    color: '#5B8EAD',
    order: 2,
    active: true,
    perks: [
      'Всё из Baron',
      'Префикс §b[Guard]§r в чате',
      'Цветной ник (голубой)',
      'Приват до 5 чанков',
      'Кит /kit guard раз в 2 дня',
      'Команда /nick — псевдоним в чате',
      'Команда /fly в лобби и на спавне',
      'Команда /sit — сесть в любом месте',
      'Кастомный тег в Discord-сервере',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 149, commands: ['lp user {username} parent addtemp guard 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 399, commands: ['lp user {username} parent addtemp guard 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 799, commands: ['lp user {username} parent add guard'] },
    ],
  },
  {
    id: 'hero',
    slug: 'hero',
    name: 'Hero',
    description: 'Самый популярный ранг. Оптимальный баланс цены, привилегий и удобства игры.',
    color: '#4CAF50',
    order: 3,
    active: true,
    badge: 'ТОП ПРОДАЖ',
    popular: true,
    perks: [
      'Всё из Guard',
      'Префикс §a[Hero]§r в чате',
      'Цветной ник (зелёный)',
      'Приват до 10 чанков',
      'Кит /kit hero раз в 1 день',
      'Команда /workbench — верстак в кармане',
      'Команда /enderchest — эндер-сундук в кармане',
      'Команда /anvil — наковальня в кармане',
      'Цветные сообщения в чате',
      'Приоритет подключения (+2 к лимиту)',
      'Сохранение инвентаря после смерти (1 раз в 7 дней)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 249, commands: ['lp user {username} parent addtemp hero 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 649, commands: ['lp user {username} parent addtemp hero 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1299, commands: ['lp user {username} parent add hero'] },
    ],
  },
  {
    id: 'aspid',
    slug: 'aspid',
    name: 'Aspid',
    description: 'Продвинутый ранг для серьёзных игроков. Выживай дольше, добывай эффективнее.',
    color: '#9C27B0',
    order: 4,
    active: true,
    perks: [
      'Всё из Hero',
      'Префикс §d[Aspid]§r в чате',
      'Цветной ник (фиолетовый)',
      'Приват до 20 чанков',
      'Кит /kit aspid раз в 12 часов',
      'Команда /feed — насытиться (раз в 5 мин)',
      'Команда /heal — восстановить здоровье (раз в 10 мин)',
      'Команда /pweather — изменить погоду для себя',
      'Команда /ptime — изменить время суток для себя',
      'Приоритет подключения (+3 к лимиту)',
      'Сохранение инвентаря после смерти (3 раза в неделю)',
      'Доп. слоты в аукционе',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 349, commands: ['lp user {username} parent addtemp aspid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 899, commands: ['lp user {username} parent addtemp aspid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 1799, commands: ['lp user {username} parent add aspid'] },
    ],
  },
  {
    id: 'squid',
    slug: 'squid',
    name: 'Squid',
    description: 'Высокий ранг с полётом и расширенными возможностями телепортации.',
    color: '#FF9800',
    order: 5,
    active: true,
    badge: 'ВЫГОДНО',
    perks: [
      'Всё из Aspid',
      'Префикс §6[Squid]§r в чате',
      'Цветной ник (оранжевый)',
      'Приват до 30 чанков',
      'Кит /kit squid раз в 6 часов',
      'Команда /fly на выживании (вне PvP-боя)',
      'Команда /tp — телепорт к игрокам',
      'Команда /tpa — запросить телепорт',
      'Команда /speed — изменить скорость передвижения',
      'Команда /near — список игроков рядом',
      'Выделение в TAB списке игроков',
      'Доступ к /kit seasonal (сезонный кит)',
      'Сохранение инвентаря после смерти (без ограничений)',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 499, commands: ['lp user {username} parent addtemp squid 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1299, commands: ['lp user {username} parent addtemp squid 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 2599, commands: ['lp user {username} parent add squid'] },
    ],
  },
  {
    id: 'head',
    slug: 'head',
    name: 'Head',
    description: 'Почти максимальный ранг. Эксклюзивные функции, личный Discord и максимальный комфорт.',
    color: '#F44336',
    order: 6,
    active: true,
    perks: [
      'Всё из Squid',
      'Префикс §c[Head]§r в чате',
      'Цветной ник (красный)',
      'Приват до 50 чанков',
      'Кит /kit head раз в 3 часа',
      'Команда /god — режим бога (1 раз в сутки, 30 мин)',
      'Команда /invsee — просмотр инвентаря игрока',
      'Команда /echest — открыть свой эндер-сундук',
      'Команда /trash — корзина для мусора',
      'Команда /condense — сжать предметы в блоки',
      'Отдельный VIP-чат только для привилегий',
      'Личный текстовый канал в Discord',
      'x2 опыт с убийства мобов',
      'Топ-приоритет подключения к серверу',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 699, commands: ['lp user {username} parent addtemp head 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 1799, commands: ['lp user {username} parent addtemp head 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 3599, commands: ['lp user {username} parent add head'] },
    ],
  },
  {
    id: 'elite',
    slug: 'elite',
    name: 'Elite',
    description: 'Абсолютный максимум NATUX WORLD. Все привилегии, все команды, статус легенды сервера.',
    color: '#FF2B4F',
    order: 7,
    active: true,
    badge: 'МАКСИМУМ',
    perks: [
      'Всё из Head',
      'Префикс §4[ELITE]§r в чате (анимированный)',
      'Кастомный ник-цвет на выбор',
      'Безлимитный приват',
      'Кит /kit elite раз в 1 час',
      'Все командные привилегии сервера',
      'Команда /hat — любой блок или голова моба',
      'Команда /nick с RGB-форматированием',
      'Команда /broadcast — объявление на весь сервер (1 раз в день)',
      'x3 опыт с убийства мобов',
      'Дроп редкого лута +50%',
      'Личный голосовой канал в Discord',
      'Значок Elite на сайте',
      'Позиция №1 в TAB-листе',
      'Эксклюзивный cosmetic-набор',
      'Ранний доступ к обновлениям',
    ],
    variants: [
      { duration: '30d', durationLabel: '30 дней', price: 999, commands: ['lp user {username} parent addtemp elite 30d accumulate'] },
      { duration: '90d', durationLabel: '90 дней', price: 2499, commands: ['lp user {username} parent addtemp elite 90d accumulate'] },
      { duration: 'forever', durationLabel: 'Навсегда', price: 4999, commands: ['lp user {username} parent add elite'] },
    ],
  },
]
